/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-06-07 04:10:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/E:/maven/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685925212367L));
    _jspx_dependants.put("jar:file:/E:/maven/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fapp_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fapp_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fapp_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- JSTL 표현식으로 리스트 출력 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 배열 갯수를 확인하는 라이브러리 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
 int z = (int)(request.getAttribute("totals")); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시판 리스트</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/notice.css?v=3\">\r\n");
      out.write("<style>\r\n");
      out.write(".btn { width:100px; height:30px; background-color: black;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<ol class=\"olcss\">\r\n");
      out.write("		<li>번호</li>\r\n");
      out.write("		<li>제목</li>\r\n");
      out.write("		<li>글쓴이</li>\r\n");
      out.write("		<li>등록일</li>\r\n");
      out.write("	</ol>\r\n");
      out.write("	<!-- 찾을 내용이 없을 경우 또는 게시글이 하나도 없을 경우 -->\r\n");
      out.write("	");
      if (_jspx_meth_app_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_app_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');

	int now_page = (int)(request.getAttribute("now_page"));

      out.write("\r\n");
      out.write("	<!-- 반복문 적용 JSTL : forEach -->\r\n");
      out.write("	<!-- 게시물에 표시되는 넘버 번호 공식 : 전체데이터 갯수 - (현재페이지번호 - 1) * 한페이지당 출력 수 -->\r\n");
      out.write("	");
      //  app:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_app_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_app_005fset_005f1_reused = false;
      try {
        _jspx_th_app_005fset_005f1.setPageContext(_jspx_page_context);
        _jspx_th_app_005fset_005f1.setParent(null);
        // /notice_list.jsp(43,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_app_005fset_005f1.setVar("w");
        // /notice_list.jsp(43,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_app_005fset_005f1.setValue(z-(now_page-1)*2);
        int _jspx_eval_app_005fset_005f1 = _jspx_th_app_005fset_005f1.doStartTag();
        if (_jspx_th_app_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_app_005fset_005f1);
        _jspx_th_app_005fset_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_app_005fset_005f1_reused);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_app_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<!-- 반복문 적용 -->\r\n");
      out.write("\r\n");
      out.write("	<!-- 페이징 번호 -->\r\n");
      out.write("	<div class=\"pageing\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			");

//페이징 계산 수식구
int pg = (int)Math.ceil(z / 2f);

int w = 1;
while(w <= pg){

      out.write("\r\n");
      out.write("			<li onclick=\"pageing(");
      out.print(w);
      out.write(')');
      out.write('"');
      out.write('>');
      out.print(w);
      out.write("</li>\r\n");
      out.write("			");

w++;
}

      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 페이징 번호 -->\r\n");
      out.write("\r\n");
      out.write("	<!-- 게시물 검색 -->\r\n");
      out.write("	<form id=\"frm\" onsubmit=\"return sh()\" method=\"get\"\r\n");
      out.write("		action=\"./notice_list.do\">\r\n");
      out.write("		<div class=\"div_search\">\r\n");
      out.write("			제목 검색 : <input type=\"text\" name=\"search\"> <input\r\n");
      out.write("				type=\"submit\" value=\"게시물 검색\"> <input type=\"button\"\r\n");
      out.write("				value=\"전체목록\" onclick=\"gopage()\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<div class=\"div_search\">\r\n");
      out.write("		<input type=\"button\" value=\"글쓰기\" class=\"btn\"\r\n");
      out.write("			onclick=\"location.href='./notice_write.html';\">\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	//게시판 제목 클릭시 해당 페이지로 자동증가값이 전달 되도록 합니다.\r\n");
      out.write("	function notice_view(idx){\r\n");
      out.write("		location.href='./notice_view.do?nidx='+idx;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	function pageing(no){\r\n");
      out.write("		location.href='./notice_list.do?page='+no;		\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function gopage(){\r\n");
      out.write("		location.href='./notice_list.do';\r\n");
      out.write("	}\r\n");
      out.write("	function sh(){\r\n");
      out.write("		if(frm.search.value==\"\"){\r\n");
      out.write("			alert(\"검색한 단어를 입력해 주세요\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}	\r\n");
      out.write("		else{\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_app_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  app:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_app_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_app_005fset_005f0_reused = false;
    try {
      _jspx_th_app_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_app_005fset_005f0.setParent(null);
      // /notice_list.jsp(31,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fset_005f0.setVar("ea");
      // /notice_list.jsp(31,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_app_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/notice_list.jsp(31,1) '${fn:length(noticelist)}'",_jsp_getExpressionFactory().createValueExpression(new org.apache.jasper.el.ELContextWrapper(_jspx_page_context.getELContext(),_jspx_fnmap_0),"${fn:length(noticelist)}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_app_005fset_005f0 = _jspx_th_app_005fset_005f0.doStartTag();
      if (_jspx_th_app_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_app_005fset_005f0);
      _jspx_th_app_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_app_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_app_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  app:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_app_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fapp_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_app_005fif_005f0_reused = false;
    try {
      _jspx_th_app_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_app_005fif_005f0.setParent(null);
      // /notice_list.jsp(32,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ea==0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_app_005fif_005f0 = _jspx_th_app_005fif_005f0.doStartTag();
      if (_jspx_eval_app_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<!-- jstl 조건문 -->\r\n");
          out.write("		<ol class=\"olcss css2\">\r\n");
          out.write("			<li style=\"width: 100%;\">찾고자 하는 게시물 또는 등록된 게시물이 없습니다.</li>\r\n");
          out.write("		</ol>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_app_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_app_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fapp_005fif_0026_005ftest.reuse(_jspx_th_app_005fif_005f0);
      _jspx_th_app_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_app_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_app_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  app:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_app_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_app_005fforEach_005f0_reused = false;
    try {
      _jspx_th_app_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_app_005fforEach_005f0.setParent(null);
      // /notice_list.jsp(44,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f0.setVar("item");
      // /notice_list.jsp(44,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_app_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/notice_list.jsp(44,1) '${noticelist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${noticelist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_app_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_app_005fforEach_005f0 = _jspx_th_app_005fforEach_005f0.doStartTag();
        if (_jspx_eval_app_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		<ol class=\"olcss css2\">\r\n");
            out.write("			<li>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${w}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("			<!-- 게시판 제목 -->\r\n");
            out.write("			<li style=\"text-align: left; text-indent: 10px;\"\r\n");
            out.write("				onclick=\"notice_view('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item[0]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("			<li>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item[2]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("			<!-- fn을 이용해서 글자를 자르는 파트 -->\r\n");
            out.write("			");
            if (_jspx_meth_app_005fset_005f2(_jspx_th_app_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_app_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("			<li>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("		</ol>\r\n");
            out.write("		");
            if (_jspx_meth_app_005fset_005f3(_jspx_th_app_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_app_005fforEach_005f0))
              return true;
            out.write('\r');
            out.write('\n');
            out.write('	');
            int evalDoAfterBody = _jspx_th_app_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_app_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_app_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_app_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_app_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fapp_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_app_005fforEach_005f0);
      _jspx_th_app_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_app_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_app_005fset_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_app_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_app_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  app:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_app_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_app_005fset_005f2_reused = false;
    try {
      _jspx_th_app_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_app_005fset_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_app_005fforEach_005f0);
      // /notice_list.jsp(52,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fset_005f2.setVar("date");
      // /notice_list.jsp(52,3) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_app_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/notice_list.jsp(52,3) '${fn:substring(item[3],0,10)}'",_jsp_getExpressionFactory().createValueExpression(new org.apache.jasper.el.ELContextWrapper(_jspx_page_context.getELContext(),_jspx_fnmap_1),"${fn:substring(item[3],0,10)}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_app_005fset_005f2 = _jspx_th_app_005fset_005f2.doStartTag();
      if (_jspx_th_app_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_app_005fset_005f2);
      _jspx_th_app_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_app_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_app_005fset_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_app_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_app_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  app:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_app_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_app_005fset_005f3_reused = false;
    try {
      _jspx_th_app_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_app_005fset_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_app_005fforEach_005f0);
      // /notice_list.jsp(55,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_app_005fset_005f3.setVar("w");
      // /notice_list.jsp(55,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_app_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/notice_list.jsp(55,2) '${w-1}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${w-1}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_app_005fset_005f3 = _jspx_th_app_005fset_005f3.doStartTag();
      if (_jspx_th_app_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fapp_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_app_005fset_005f3);
      _jspx_th_app_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_app_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_app_005fset_005f3_reused);
    }
    return false;
  }
}
